# -*- coding: utf-8 -*-
"""Export_raw_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMg9abBqblprpFN9QWhP9s2iOMMwl8VQ
"""

import os

# Path to your "Project Data" folder on Google Drive
output_folder = "/content/drive/MyDrive/Project Data"
os.makedirs(output_folder, exist_ok=True)

print("Export folder:", output_folder)

import pandas as pd
from sqlalchemy import create_engine, text

DB_URL = "postgresql+psycopg2://Test:bQNxVzJL4g6u@ep-noisy-flower-846766.us-east-2.aws.neon.tech/TravelTide?sslmode=require"
engine = create_engine(DB_URL, pool_pre_ping=True)

# Get list of tables
with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema='public'
    """))
    tables = [row[0] for row in result]

print("Tables found:", tables)

# Export each table as CSV into Google Drive
for table in tables:
    print(f"Exporting {table}...")
    df = pd.read_sql(f'SELECT * FROM "{table}"', engine)
    filename = os.path.join(output_folder, f"{table}.csv")
    df.to_csv(filename, index=False)
    print(f"✅ Saved {filename}")

